# Generated by Django 5.2.1 on 2025-05-15 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_useraccount_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useraccount',
            options={'ordering': ['user'], 'verbose_name': 'User Account', 'verbose_name_plural': 'User Accounts'},
        ),
        migrations.RemoveIndex(
            model_name='useraccount',
            name='user_accoun_user_id_c5dc4e_idx',
        ),
        migrations.RenameField(
            model_name='useraccount',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AddIndex(
            model_name='useraccount',
            index=models.Index(fields=['user'], name='user_accoun_user_id_32ff6e_idx'),
        ),
    ]
