# Generated by Django 5.2.1 on 2025-05-17 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_useraccount_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='token',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='token_expiry',
        ),
        migrations.AddField(
            model_name='useraccount',
            name='token_generated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='inactive', max_length=20),
        ),
    ]
